### ISSUE TITLE
images to readme

### ISSUE THREAD

**Issue by sushant-jain** [sushant-jain/pinkcabs#1]
![whatsapp-image2-20161016](https://cloud.githubusercontent.com/assets/20531132/19442277/6ea3300e-94a6-11e6-926c-9e8b72e1f31c.jpeg)
![whatsapp-image3-20161016](https://cloud.githubusercontent.com/assets/20531132/19442276/6e934518-94a6-11e6-85a5-d9963c481289.jpeg)
![whatsapp-image-20161016](https://cloud.githubusercontent.com/assets/20531132/19442278/6ea4bbd6-94a6-11e6-8dac-be20691acde1.jpeg)

**Comment by vishal-wadhwa** [comment]
@sushant-jain Where is the  link button for these screen shots?

**Comment by sushant-jain** [comment]
ruk jaa bhai
itni jaldi kya hai

**Comment by jtgupta** [comment]
bhai chota karke daalne the screenshot
